version: '3.2'

services:
  dev:
    container_name: php-reports-dev
    build: .
    volumes:
      - .:/var/www/laravel-reports
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_LOG_LEVEL=debug
      - APP_KEY=base64:KvZh3SiY8giri/3Qyt+wARkbG9Ssy7+MpxP9k7CgyTo=
      - DB_DATABASE=employees
      - DB_USERNAME=employees
      - DB_PASSWORD=employees
      - DB_HOST=mysql
  mysql:
    image: mysql:5.7
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_USER=employees
     - MYSQL_PASSWORD=employees
     - MYSQL_DATABASE=employees
    ports:
     - "3306:3306"
  adminer:
    image: adminer
    ports:
      - 8010:8080
